workflows:
  ios-build:
    name: iOS App Store Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Increment iOS build number
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "com.mycompany.medmax" --platform IOS)
          if [ -z "$LATEST_BUILD_NUMBER" ]; then
            LATEST_BUILD_NUMBER=0
          fi
          NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          echo "New build number: $NEW_BUILD_NUMBER"
          flutter build ipa --release --build-name=1.1.3 --build-number=$NEW_BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
